osx_image: xcode8.3
language: swift

script:
  - xcodebuild clean build -scheme Payment -workspace Payment.xcworkspace -sdk iphonesimulator -destination 'name=iPhone SE,OS=10.2'
  - xcodebuild test -scheme Payment -workspace Payment.xcworkspace -sdk iphonesimulator -destination 'name=iPhone SE,OS=10.2' CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
